export const locationsMock = [
  { id: "loc-1", name: "Krkonoše" },
  { id: "loc-2", name: "Šumava" },
  { id: "loc-3", name: "Beskydy" },
];

export const tripsMock = [
  {
    id: "trip-1",
    ascent: 650,
    descent: 650,
    header: "Sněžka z Pece",
    image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=60",
    info: "Klasický výstup na nejvyšší horu ČR. Trasa je dobře značená.",
    location_id: "loc-1",
    hikeTimeRange: { value: 5, unit: "h" },
    carTimeRange: { value: 3, unit: "h" },
    hikeLength: { value: 15, unit: "km" },
    startPoint: { lat: 50.693, lng: 15.739 },
    map: "https://mapy.cz/s/snezka",
    mapPreview: "/images/maps/snezka-preview.jpg",
    parking: "Pec pod Sněžkou - centrální parkoviště",
  },
  {
    id: "trip-2",
    ascent: 420,
    descent: 420,
    header: "Černé a Čertovo jezero",
    image: "https://images.unsplash.com/photo-1500048993953-d23a436266cf?auto=format&fit=crop&w=1200&q=60",
    info: "Nenáročná tůra okolo ledovcových jezer na Šumavě.",
    location_id: "loc-2",
    hikeTimeRange: { value: 3, unit: "h" },
    carTimeRange: { value: 2, unit: "h" },
    hikeLength: { value: 10, unit: "km" },
    startPoint: { lat: 49.163, lng: 13.200 },
    map: "https://mapy.cz/s/cerne-certovo",
    mapPreview: "/images/maps/cerne-certovo-preview.jpg",
    parking: "Parkoviště Špičák",
  },
  {
    id: "trip-3",
    ascent: 800,
    descent: 800,
    header: "Lysá hora okruh",
    image: "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=60",
    info: "Výživný okruh na nejvyšší vrchol Beskyd s krásnými výhledy.",
    location_id: "loc-3",
    hikeTimeRange: { value: 6, unit: "h" },
    carTimeRange: { value: 3, unit: "h" },
    hikeLength: { value: 20, unit: "km" },
    startPoint: { lat: 49.544, lng: 18.390 },
    map: "https://mapy.cz/s/lysa-hora",
    mapPreview: "/images/maps/lysa-hora-preview.jpg",
    parking: "Ostravice - parkoviště u nádraží",
  },
];
